export type StyleRelease = {
  key: string;
  title: string;
  style: string;
  palette: string;
  rendering: string;
  specification: {
    visualIdentity: string;
    pixelTechnique: string;
    shapeLanguage: string;
    paletteAndLighting: string;
    characterDirection: string;
    environmentDirection: string;
    propDirection: string;
    effectsDirection: string;
    uiHudDirection: string;
    animationDirection: string;
    accessibility: string;
  };
};

const sharedSpecification = {
  characterDirection: 'Build clearly adult characters with natural anatomy, practical layered equipment, grounded poses, and silhouettes that remain distinct at thumbnail size.',
  environmentDirection: 'Compose maps around immediately legible traversal hierarchy, routes that continue beyond the frame, useful landmarks, and generous walkable space.',
  propDirection: 'Give every prop a clear gameplay purpose, readable material grouping, and a silhouette that survives at gameplay scale without decorative clutter.',
  effectsDirection: 'Keep effects compact, high contrast, and brief so they communicate timing without obscuring characters, landmarks, or traversal.',
  uiHudDirection: 'Use compact panels, high-contrast icons, plain readable labels, and restrained ornament; interface meaning must never depend on the preview images.',
  accessibility: 'Maintain value separation between walkable terrain, obstacles, characters, and interaction targets; never rely on hue alone, and avoid flicker or visually noisy backgrounds.',
};

export const STYLE_RELEASES: readonly StyleRelease[] = [
  { key: 'pixel-art@2', title: 'Pixel Art', style: 'polished modern pixel art with crisp native-resolution clusters, clear silhouettes, and controlled material-colored outlines', palette: 'fresh greens, clear river blue, warm timber, terracotta accents, pale gold daylight', rendering: 'no antialiasing, deliberate pixel clusters, two to four shade steps per material, restrained dithering', specification: { ...sharedSpecification, visualIdentity: 'Welcoming top-down adventure pixel art with practical landmarks, open routes, calm exploration, and intentional pixel clusters as the dominant visual read.', pixelTechnique: 'Use crisp native-resolution pixel clusters without antialiasing, material-colored contours, selective internal outlines, two to four shade steps per material, and restrained dithering.', shapeLanguage: 'Favor clean stepped silhouettes, breathable clusters, broad primary paths, compact secondary details, and off-center landmarks.', paletteAndLighting: 'Use fresh greens, clear blues, honey timber, warm gray stone, terracotta accents, and pale golden daylight with short pixel-defined shadows.', animationDirection: 'Animate on an integer pixel grid with economical key poses, stable volumes, intentional holds, and no subpixel interpolation.' } },
  { key: 'flat-graphic-2d@1', title: 'Flat Graphic 2D', style: 'clean flat graphic 2D game illustration with bold geometric silhouettes, layered shapes, and restrained linework', palette: 'verdant green, cyan blue, coral, mustard, charcoal, off-white', rendering: 'crisp vector-like edges, minimal texture, broad color planes, subtle flat shadows', specification: { ...sharedSpecification, visualIdentity: 'Bright graphic 2D worlds built from confident geometric silhouettes, broad color planes, and a quiet editorial clarity that reads immediately.', pixelTechnique: 'Use crisp vector-like edges, minimal surface texture, broad unbroken fills, restrained linework, and one subtle flat shadow layer.', shapeLanguage: 'Build scenes from rounded rectangles, wedges, arcs, and asymmetric layered masses with generous negative space and clearly separated silhouettes.', paletteAndLighting: 'Use verdant green, cyan blue, coral, mustard, charcoal, and off-white with restrained flat shadows and no realistic light falloff.', animationDirection: 'Animate with clean pose-to-pose transitions, graphic smears, simple easing, and stable shape proportions without texture crawl.' } },
  { key: 'hand-painted-2d@1', title: 'Hand-Painted 2D', style: 'warm hand-painted 2D game illustration with visible brush texture, softened edges, and storybook environmental detail', palette: 'moss green, river blue, warm umber, muted coral, sunlit ochre', rendering: 'layered opaque brushwork, selective detail, painterly light, readable value grouping', specification: { ...sharedSpecification, visualIdentity: 'Warm painterly 2D adventure art with visible brushwork, softened natural edges, selective detail, and a calm illustrated-world atmosphere.', pixelTechnique: 'Use layered opaque brushwork, visible but controlled strokes, softened edge hierarchy, painterly light transitions, and crisp accents only at focal points.', shapeLanguage: 'Combine broad organic masses with tapered structures, irregular foliage rhythms, and selectively sharpened landmark silhouettes.', paletteAndLighting: 'Use moss green, river blue, warm umber, muted coral, and sunlit ochre with grouped values and warm directional light.', animationDirection: 'Animate with expressive held poses, softly painted replacement shapes, restrained secondary motion, and consistent brush texture across frames.' } },
  { key: 'cel-shaded-3d@1', title: 'Cel-Shaded 3D', style: 'stylized cel-shaded 3D game render with smooth modeled forms, graphic ink accents, and two-step lighting', palette: 'saturated green, bright blue, warm wood, orange-red accents, cool gray', rendering: 'smooth 3D geometry, hard shadow bands, selective outlines, polished materials without photorealism', specification: { ...sharedSpecification, visualIdentity: 'Polished stylized 3D forms presented through graphic light bands, selective ink accents, clean silhouettes, and energetic color separation.', pixelTechnique: 'Use smooth modeled surfaces, two-step cel lighting, hard shadow boundaries, selective contour accents, and simplified non-photoreal materials.', shapeLanguage: 'Favor smooth tapered volumes, readable bevels, sweeping curves, and decisive silhouette breaks while avoiding visible polygon faceting.', paletteAndLighting: 'Use saturated green, bright blue, warm wood, orange-red accents, and cool gray with a hard two-band key light and restrained rim light.', animationDirection: 'Animate with strong 3D key poses, readable arcs, short graphic holds, stable outlines, and deliberate transitions between light bands.' } },
  { key: 'low-poly-3d@1', title: 'Low-Poly 3D', style: 'stylized low-poly 3D game render with deliberately faceted geometry, clean silhouettes, and compact modular forms', palette: 'pine green, turquoise blue, honey wood, clay red, stone gray', rendering: 'visible polygon facets, flat-shaded surfaces, soft ambient occlusion, no ink outlines and no cel bands', specification: { ...sharedSpecification, visualIdentity: 'Compact stylized 3D worlds defined by deliberate polygon facets, modular construction, clean silhouettes, and tactile miniature-like staging.', pixelTechnique: 'Use visibly faceted low-density geometry, flat-shaded surfaces, soft ambient occlusion, no ink outlines, no cel-light bands, and no photoreal texture maps.', shapeLanguage: 'Build with planar wedges, chamfered blocks, low-sided cylinders, and asymmetric modular clusters whose facets remain visible at thumbnail size.', paletteAndLighting: 'Use pine green, turquoise blue, honey wood, clay red, and stone gray with soft environmental light that reveals each polygon plane.', animationDirection: 'Animate with clear 3D poses, economical joint motion, stable faceted volumes, and restrained secondary movement suited to modular rigs.' } },
] as const;

const commonAvoid = 'No text, letters, numbers, signs with writing, logo, watermark, UI, frame, combat, weapon, horror, gore, ruins, dark fog, childlike anatomy, extra limbs, malformed hands, franchise imitation, artist imitation, or copyrighted character.';

export function stylePrompt(release: StyleRelease, kind: 'map' | 'character', variant: number): string {
  const shared = `Use case: stylized-concept. Asset type: Game Art Style comparison preview. Style/medium: ${release.style}. Color palette: ${release.palette}. Rendering technique: ${release.rendering}.`;
  if (kind === 'map') return `${shared} Primary request: a welcoming riverside village map in bright late-morning light. Composition/framing: wide 3:2 top-down three-quarter orthographic view; a broad diagonal dirt path crosses a clear blue river on a small wooden bridge; secondary paths branch toward open frame edges; include a timber workshop, practical gardens, warm stone, compact homes, and generous walkable space. Route hierarchy and landmarks must read at thumbnail size. Variant ${variant}: vary building grouping and bridge approach while preserving the exact subject. Constraints: no people or creatures. ${commonAvoid}`;
  return `${shared} Primary request: a clearly adult field cartographer, full body, practical layered field jacket, sturdy boots, compact satchel, rolled blank map case, compass and harmless survey tools. Composition/framing: centered three-quarter standing pose, entire silhouette visible with generous padding, simple neutral backdrop, friendly focused expression, natural adult anatomy. Variant ${variant}: vary pose and equipment arrangement while preserving the exact subject. ${commonAvoid}`;
}
